### PR TITLE
example: base for libp2p mapper

### PR DESCRIPTION
**Pull request by daviddias**
Check it working at: https://ipfs.io/ipfs/QmWtSgpCBJJNwy3MDNinyG4JV35UP37ruqpUEir9AU2PSf/

### CODE REVIEW

**Comment by diasdavid** [comment]
Situations found by making this example

- [x] browserify and libp2p-crypto-secp256k1 (solved, critical)
- [ ] https://github.com/multiformats/js-multistream-select/issues/35
- [ ] https://github.com/libp2p/js-libp2p-secio/issues/62

**Comment by diasdavid** [comment]
@jbenet check this out https://ipfs.io/ipfs/QmWtSgpCBJJNwy3MDNinyG4JV35UP37ruqpUEir9AU2PSf/

**Comment by jbenet** [comment]
looks like it wasn't pinned

**Comment by diasdavid** [comment]
There you go:

https://ipfs.io/ipfs/Qmb19dkr5uMN8Hi13SBifeZwbAVYBYSE41nzDusUZg6MHY/

image

**Pull request merged**
